services:
  - type: web
    name: jobconnect-api
    runtime: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    dockerContext: .
    dockerCommand: /bin/sh -c 'python manage.py migrate --noinput && python manage.py collectstatic --noinput && python manage.py bootstrap_admin && exec uvicorn api.main:app --host 0.0.0.0 --port "$PORT"'
    healthCheckPath: /api/v1/health
    envVars:
      - key: POSTGRES_DB
        sync: false
      - key: POSTGRES_USER
        sync: false
      - key: POSTGRES_PASSWORD
        sync: false
      - key: POSTGRES_HOST
        sync: false
      - key: POSTGRES_PORT
        sync: false
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: JWT_ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"
      - key: RESUME_STORAGE_DIR
        value: /app/media/resumes
      - key: MAX_RESUME_SIZE_BYTES
        value: "5242880"
      - key: DJANGO_SUPERUSER_USERNAME
        sync: false
      - key: DJANGO_SUPERUSER_EMAIL
        sync: false
      - key: DJANGO_SUPERUSER_PASSWORD
        sync: false

  - type: web
    name: jobconnect-frontend
    runtime: docker
    plan: free
    region: singapore
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: ./frontend
    envVars:
      - key: API_BASE_URL
        value: https://jobconnect-testing-platform.onrender.com
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
